name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "master", "staging", "*.*-dev" ]
  pull_request:
    branches: [ "master", "staging", "*.*-dev" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make build

    - name: Run distcheck
      run: make clean
